name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Production
        env:
          PRODUCTION_ENV: "true"
        run: |
          # Add your deployment script here
          # For example, you can use rsync to deploy to a remote server
          # rsync -avz -e ssh ./root@remote-server:/var/www/html
